language: cpp
compiler:
  - gcc
  - clang
dist: focal

script:
  - cd formatter_lib && cmake -S . -B _build && cmake --build _build
  - cd ../formatter_ex_lib && cmake -S . -B _build && cmake --build _build
  - cd ../hello_world_application && cmake -S . -B _build && cmake --build _build && ./_build/hello_world
  - cd ../solver_lib && cmake -S . -B _build && cmake --build _build
  - cd ../solver_application && cmake -S . -B _build && cmake --build _build && ./_build/solver
