name: CMake Build
on: [push]

jobs:
  build:
    strategy:
      matrix:
        # Описываем комбинации ОС и компиляторов, которые нам нужны
        include:
          - os: ubuntu-latest
            compiler: gcc
            cc: gcc
            cxx: g++
          - os: ubuntu-latest
            compiler: clang
            cc: clang
            cxx: clang++
          - os: windows-latest
            compiler: msvc
            cc: cl
            cxx: cl

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      # Используем современный кроссплатформенный синтаксис -S . -B _build
      # Он отлично переваривается и Bash на Linux, и PowerShell на Windows
      - name: Configure CMake
        env:
          CC: ${{ matrix.cc }}
          CXX: ${{ matrix.cxx }}
        run: cmake -S . -B _build

      - name: Build Project
        run: cmake --build _build

