name: C++ CI (CMake)

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            cpp_compiler: g++
          - os: ubuntu-latest
            cpp_compiler: clang++
          - os: windows-latest
            cpp_compiler: cl
        exclude:
          - os: ubuntu-latest
            cpp_compiler: cl
          - os: windows-latest
            cpp_compiler: g++
          - os: windows-latest
            cpp_compiler: clang++

    steps:
      - uses: actions/checkout@v4

      - name: Build formatter_lib
        run: |
          cmake -S formatter_lib -B formatter_lib/_build -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          cmake --build formatter_lib/_build --config Release

      - name: Build formatter_ex_lib
        run: |
          cmake -S formatter_ex_lib -B formatter_ex_lib/_build -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          cmake --build formatter_ex_lib/_build --config Release

      - name: Build hello_world_application
        run: |
          cmake -S hello_world_application -B hello_world_application/_build -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          cmake --build hello_world_application/_build --config Release

      - name: Build solver_lib
        run: |
          cmake -S solver_lib -B solver_lib/_build -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          cmake --build solver_lib/_build --config Release

      - name: Build solver_application
        run: |
          cmake -S solver_application -B solver_application/_build -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          cmake --build solver_application/_build --config Release

      - name: Run hello_world
        run: ./hello_world_application/_build/hello_world
        if: runner.os == 'Linux'

      - name: Run solver
        run: ./solver_application/_build/solver
        if: runner.os == 'Linux'
